export type OnboardingData = {
  prenom: string;
  age: string;
  pays: string;
  ville: string;
  niveauTrading: 'debutant' | 'intermediaire' | 'avance' | 'expert';
  anneesExperience: '0' | '1-2' | '3-5' | '5+';
  aDejaPerduCapital: boolean | null;
  sourceApprentissage: string[];
  marchesTraites: string[];
  marchePrefere: string;
  styleTrading: 'scalp' | 'day' | 'swing' | 'position';
  plateformesUtilisees: string[];
  capitalDisponibleFCFA: string;
  revenuMensuelFCFA: string;
  pourcentageCapitalRisque: string;
  objectifMensuelFCFA: string;
  tradingEstRevenuPrincipal: boolean | null;
  reactionPerteRapide: string;
  comportementApresDefaite: string;
  reactionFOMO: string;
  respecteSL: string;
  patientAvantEntree: string;
  gestionStress: string;
  heuresParJour: string;
  sessionsPreferees: string[];
  joursDisponibles: string[];
  fuseauHoraire: string;
  objectifPrincipal: string;
};
